source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

gem 'activeadmin', github: 'activeadmin'
# gem 'inherited_resources', github: 'josevalim/inherited_resources'
# gem "jquery_datepicker", github: "foodforarabbit/jquery_datepicker", ref: "636331e04a9e39e3a367af6ae548837d0b2fa20b"

gem 'therubyracer'
gem 'mysql2'
gem 'devise'
# gem 'delayed_job'
gem 'easy_roles'
# gem 'formtastic'
gem 'gritter'
gem 'json'
gem 'launchy'
gem 'mime-types'
# gem 'rmagick'
gem 'paperclip'
# gem 'psych'
# gem 'jbuilder', '~> 2.0'
gem 'stateflow'
# gem 'best_in_place'
gem 'mail'
# gem 'postmark-rails'
# gem 'roo'
# gem 'ffi'

# PDF gems
# gem 'wicked_pdf'
gem 'prawn'

# Asset gems
gem 'sass'
gem 'sprockets', '2.11.0'
gem 'sprockets-rails'
gem 'sass-rails', '4.0.2'
gem 'bootstrap-sass'
gem "compass-rails"
# gem 'bourbon'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

# Jquery AJAX gems
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'

# Rails 4 gems
gem 'activerecord-deprecated_finders'
# gem 'autoprefixer-rails'
# gem 'protected_attributes'
# gem 'rails-deprecated_sanitizer'
# gem 'responders'

group :development, :test do
  gem 'rspec-rails'  
  gem 'capybara'
  gem 'capybara-webkit'  
  gem 'guard-rspec'
  # gem 'guard-livereload'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'  
  gem 'database_cleaner'
  
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  # gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'  
  gem 'debug_inspector'
  gem 'terminal-notifier-guard'
  gem 'rb-fsevent'
  gem 'pry'
  gem 'spork'
  gem 'letter_opener'
  gem 'quiet_assets', '1.1.0'
  gem 'sqlite3'
end

# gem 'bootstrap', '~> 4.0.0.alpha6'
